version: 52
jobs:
- name: Build and Test
  steps:
  - type: CheckoutStep
    name: checkout code
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - type: SetupCacheStep
    name: cargo cache setup
    key: cargo-registry
    checksumFiles: Cargo.lock
    entries:
    - path: /usr/local/cargo/registry
    uploadStrategy: UPLOAD_IF_NOT_EXACT_MATCH
    condition: SUCCESSFUL
    optional: false
  - type: SetupCacheStep
    name: proj cache setup
    key: cargo-target
    entries:
    - path: target
    uploadStrategy: UPLOAD_IF_CHANGED
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: login cargo
    runInContainer: true
    image: '@server@/@project_path@/rust:latest'
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        mkdir $HOME/.cargo/
        cat << 'EOF' >> $CARGO_HOME/config.toml
        [registries.onedev]
        index = "sparse+@server_url@/@project_path@/~cargo/"
        credential-provider = "cargo:token"
        EOF
        cat $HOME/.cargo/config.toml

        echo @secret:site_docker_pusher_secret@ | cargo login --registry onedev
    runAs: 0:0
    registryLogins:
    - registryUrl: '@server_url@'
      userName: '@job_token@'
      passwordSecret: site_docker_pusher_secret
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: reject all warnings
    runInContainer: true
    image: '@server@/@project_path@/rust:latest'
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        RUSTFLAGS="-D warnings" cargo check --all-targets --all-features
        cargo clippy --all-targets --all-features -- -D warnings
    runAs: 0:0
    registryLogins:
    - registryUrl: '@server@'
      userName: site_docker_pusher
      passwordSecret: site_docker_pusher_secret
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: run cargo build
    runInContainer: true
    image: '@server@/@project_path@/rust:latest'
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        cargo build
        cargo test
    runAs: 0:0
    registryLogins:
    - registryUrl: '@server@'
      userName: site_docker_pusher
      passwordSecret: site_docker_pusher_secret
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  - type: PullRequestUpdateTrigger
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Mirror to Github
  steps:
  - type: PushRepository
    name: github
    remoteUrl: https://github.com/lry127/toykio.git
    passwordSecret: github mirror push
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Build toolchain
  steps:
  - type: CheckoutStep
    name: checkout out
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - type: BuildImageStep
    name: build toolchain image
    dockerfile: toolchain.Dockerfile
    output:
      type: RegistryOutput
      tags: '@server@/@project_path@/rust:latest'
    registryLogins:
    - registryUrl: '@server@'
      userName: site_docker_pusher
      passwordSecret: site_docker_pusher_secret
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
